TestApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;
using Microsoft.AspNet.Identity;

namespace CoursesApp.Controllers
{
    public class CourseController : Controller
    {

        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        private readonly TraineeCourseService traineeCourseService;
        private readonly IMapper mapper;

        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();
            traineeCourseService = new TraineeCourseService();

        }

        //// GET: Default
        //public ActionResult Index()
        //{
        //    var courses = courseService.ReadAll();
        //    return View(mapper.Map<List<Course>, List<CourseModel>>(courses));
        //}

        // GET: Course
        public ActionResult Index(string query = null, int? categoryId = null, int? trainerId = null)
        {
            var coursesListData = new CoursesListModel();
            InitSelectList(ref coursesListData);


            var coursesList = courseService.ReadAll(query, trainerId, categoryId);


            var mappedCoursesList = mapper.Map<List<CourseModel>>(coursesList);
            coursesListData.Courses = mappedCoursesList;


            return View(coursesListData);
        }

        public ActionResult Info(int? Id)
        {
            if (Id == null || Id == 0)
                return HttpNotFound("This course not found!");

            var courseInfo = courseService.Get(Id.Value);
            if (courseInfo == null)
                return HttpNotFound("This course not found!");

            var mappedCourseInfo = mapper.Map<Course, CourseModel>(courseInfo);

            return View(mappedCourseInfo);
        }

        [HttpPost]
        public ActionResult Subscribe(TraineeCourseModel model, int Id)
        {
            try
            {
                var course = courseService.Get(Id);

                model.CourseId = Id;
                model.Trainee_Id = Id;

                var courseTrainee = mapper.Map<Trainee_Courses>(model);

                var TraineeCourse = traineeCourseService.Create(courseTrainee);

                if (TraineeCourse >= 1)
                {
                    return Json(new { saved = true });
                }
                else
                {
                    return Json(new { saved = false });
                }
            }
            catch (Exception ex)
            {
                return Json(new { saved = false, message = ex.Message });
            }
        }


        private void InitSelectList(ref CourseModel courseModel)
        {
            var mappedCategoriesList = GetCategories();
            courseModel.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            courseModel.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private void InitSelectList(ref CoursesListModel coursesList)
        {
            var mappedCategoriesList = GetCategories();
            coursesList.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            coursesList.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private IEnumerable<CategoryModel> GetCategories()
        {
            var categories = categoryService.ReadAll();
            return mapper.Map<IEnumerable<CategoryModel>>(categories);
        }

        private IEnumerable<TrainerModel> GetTrainers()
        {
            var trainers = trainerService.ReadAll();
            return mapper.Map<IEnumerable<TrainerModel>>(trainers);
        }

    }
}

TestApp/Controllers/DefaultController.cs
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesApp.Controllers
{
    public class DefaultController : Controller
    {
        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        private readonly IMapper mapper;

        public DefaultController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();

        }

        // GET: Default
        public ActionResult Index()
        {
            var courses = courseService.ReadAll();
            var categories = categoryService.ReadAll();
            var trainers  = trainerService.ReadAll();

            CoursesListModel mymodel = new CoursesListModel();
            mymodel.Courses = mapper.Map<List<Course>, List<CourseModel>>(courses);
            mymodel.categories = mapper.Map<List<Category>, List<CategoryModel>>(categories);
            mymodel.trainers = mapper.Map<List<Trainer>, List<TrainerModel>>(trainers);

            return View(mymodel);
        }
    }
}

TestApp/Views/Shared/_CategoriesListView.cshtml
@model CoursesApp.Models.CoursesListModel

<div class="section-title">
    <h2>Our Categories</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
</div>

<div class="container px-4 px-lg-5">
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        @foreach (var categoryItem in Model.categories)
        {


            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <div class="card-body p-4">
                        <h5 class="card-title mb-3">@categoryItem.Name</h5>
                        <p class="card-text mb-0">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0 align-items-center">
                                @Html.ActionLink("View All Courses", "Index", "Course", new { categoryId = categoryItem.Id },
                        new { @class = "slide btn btn-outline-primary btn-lg px-4" })
                      
                    </div>
                </div>
            </div>
        }
    </div>
        </div>

TestApp/Views/Shared/_CoursesListView.cshtml
@model CoursesApp.Models.CoursesListModel

<div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-5">

        </div>
    </div>

    @using (Html.BeginForm("Index", "Course", FormMethod.Get, new { @class = "flex-row align-items-center flex-wrap " }))
    {
        <div class="row mb-5">
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0 select">
                @*<input type="text" class="form-control form-control-lg" placeholder="Job title, Company...">*@
                @Html.TextBoxFor(m => m.Query, new { @class = "form-control form-control-lg", placeholder = "Course..." })
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                @Html.DropDownListFor(m => m.TrainerId, Model.Trainers, "Select Trainer", new { @class = " selectpicker", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })

            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                @Html.DropDownListFor(m => m.CategoryId, Model.Categories, "Select Category", new { @class = "selectpicker", id = "job-Type", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                <button type="submit" value="Search" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Course</button>
            </div>
        </div>
    }



    @if (Model != null && Model.Courses.Count() > 0)
    {
        foreach (var courseItem in Model.Courses)
        {
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <div class="card-body p-4">
                        <img class="card-img-top" src="~/Uploads/Courses/@courseItem.Image_ID" alt="..." />
                        <h5 class="card-title mb-3">@courseItem.Name</h5>
                        <p class="card-text mb-0">@courseItem.Description</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0 align-items-center">
                        @Html.ActionLink("View course detail", "Info", "Course", new { id = courseItem.Course_Id },
                new { @class = "slide btn btn-outline-primary btn-lg px-4" })

                    </div>
                </div>
            </div>

        }
    }
    else
    {
        <tr>
            <td colspan="4">
                <div class="alert alert-danger">
                    There is no Courses found!
                </div>
            </td>
        </tr>
    }
</div>

TestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <title>Coursaty - @ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles-business.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="@Url.Action("Index", "Default")">Coursaty</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Default")">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Course")">Courses</a></li>
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="page-content">
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark" style="bottom: 0">
        <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Coursaty @DateTime.Now.Year</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.all.min.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>




</body>
</html>

TestApp/Views/Shared/_TrainersListView.cshtml
@model CoursesApp.Models.CoursesListModel


<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

<div class="section-title">
    <h2>Our Trainers</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
</div>

<div class="your-class">
    @foreach (var TrainerItem in Model.trainers)
    {

        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0">
                <div class="card-body p-4">
                    <h5 class="card-title mb-3">@TrainerItem.Name</h5>
                    <p class="card-text mb-0">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
                <div class="card-footer p-4 pt-0 bg-transparent border-top-0 align-items-center">
                    <a class="text-dark" href="@TrainerItem.Website" target="_blank">
                        <i class="fas fa-external-link fa-fw"></i>
                    </a>

                </div>
            </div>
        </div>
    }
</div>

        <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

        <script type="text/javascript">
            $('.your-class').slick({
                slidesToShow: 3,
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 1500,
                arrows: false,
                responsive: [
                    {
                        breakpoint: 980, // tablet breakpoint
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480, // mobile breakpoint
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        </script>

TestApp/Views/Shared/_UserLayout.cshtml
@{ 

    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles-business.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="@Url.Action("Index", "Default")">Coursaty</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">@Html.Partial("_LoginPartial")</li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">

        @RenderBody()

    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
</body>
</html>