TestApp/Areas/Admin/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;

namespace CoursesApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CourseController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();
        }

        // GET: Course
        public ActionResult Index(string query = null, int? categoryId = null, int? trainerId = null)
        {
            var coursesListData = new CoursesListModel();
            InitSelectList(ref coursesListData);


            var coursesList = courseService.ReadAll(query, trainerId, categoryId);


            var mappedCoursesList = mapper.Map<List<CourseModel>>(coursesList);
            coursesListData.Courses = mappedCoursesList;


            return View(coursesListData);
        }

        public ActionResult Create()
        {
            var courseModel = new CourseModel();

            InitSelectList(ref courseModel);

            return View(courseModel);
        }

        [HttpPost]
        public ActionResult Create(CourseModel courseData)
        {


            InitSelectList(ref courseData);

            try
            {
                if (ModelState.IsValid)
                {
                    courseData.Image_ID = SaveImageFile(courseData.ImageFile);


                    var courseDTO = mapper.Map<Course>(courseData);
                    courseDTO.Category = null;
                    courseDTO.Trainer = null;



                    int result = courseService.Create(courseDTO);

                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An error occurred!";
                }
                return View(courseData);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(courseData);
            }
        }

        public ActionResult Edit(int? Id)
        {
            if (Id == null)
                return HttpNotFound();


            var currentCourseData = courseService.Get(Id.Value);
            var courseModel = mapper.Map<CourseModel>(currentCourseData);


            InitSelectList(ref courseModel);
            return View(courseModel);
        }

        [HttpPost]
        public ActionResult Edit(CourseModel courseData)
        {


            InitSelectList(ref courseData);


            try
            {
                if (ModelState.IsValid)
                {


                    courseData.Image_ID = SaveImageFile(courseData.ImageFile, courseData.Image_ID);



                    var courseDTO = mapper.Map<Course>(courseData);
                    courseDTO.Category = null;
                    courseDTO.Trainer = null;


                    int result = courseService.Update(courseDTO);

                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An error occurred!";
                }
                return View(courseData);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(courseData);
            }
        }


        public ActionResult Delete(int? Id)
        {
            if (Id != null)
            {
                var course = courseService.Get(Id.Value);

                var categoryInfo = mapper.Map<CourseModel>(course);

                return View(categoryInfo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int? Id, CourseModel courseData)
        {
                var deleted = courseService.Delete(Id.Value);

            if (deleted)
            {
                return RedirectToAction("index", "Course");
            }
            return RedirectToAction("index", "Course");

        }


        private void InitSelectList(ref CourseModel courseModel)
        {
            var mappedCategoriesList = GetCategories();
            courseModel.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            courseModel.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private void InitSelectList(ref CoursesListModel coursesList)
        {
            var mappedCategoriesList = GetCategories();
            coursesList.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            coursesList.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private IEnumerable<CategoryModel> GetCategories()
        {
            var categories = categoryService.ReadAll();
            return mapper.Map<IEnumerable<CategoryModel>>(categories);
        }

        private IEnumerable<TrainerModel> GetTrainers()
        {
            var trainers = trainerService.ReadAll();
            return mapper.Map<IEnumerable<TrainerModel>>(trainers);
        }

        private string SaveImageFile(HttpPostedFileBase imageFile, string currentImageId = "" )
        {
            if (imageFile != null)
            {
              
                var fileExtenstion = Path.GetExtension(imageFile.FileName);


                var imageGuid = Guid.NewGuid().ToString();

                string imageId = imageGuid + fileExtenstion;


                //Save file
                string filePath = Server.MapPath($"~/Uploads/Courses/{imageId}");
                imageFile.SaveAs(filePath);

                //Delete old file - update action
                if (!string.IsNullOrEmpty(currentImageId))
                {
                    string oldFilePath = Server.MapPath($"~/Uploads/Courses/{currentImageId}");
                    System.IO.File.Delete(oldFilePath);
                }

                return imageId;
            }
            return currentImageId;
        }
    }
}

TestApp/Areas/Admin/Controllers/CourseUnitsController.cs
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesApp.Areas.Admin.Controllers
{
    public class CourseUnitsController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseUnitService courseUnitService;

        public CourseUnitsController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseUnitService = new CourseUnitService();

        }


        // GET: Admin/CourseUnits?courseId=1
        public ActionResult Index(int? courseId)
        {
            if (courseId == null)
                return HttpNotFound();



            var units = courseUnitService.ReadCourseUnits(courseId.Value);
            var mappedUnits = mapper.Map<IEnumerable<Course_Units>, IEnumerable<CourseUnitModel>>(units);


            ViewBag.CourseName = mappedUnits.FirstOrDefault()?.Name;
            ViewBag.Description = mappedUnits.FirstOrDefault()?.Description;
            ViewBag.CourseId = courseId;


            return View(mappedUnits);
        }

        // POST: Admin/CourseUnits/Create
        [HttpPost]
        public JsonResult Create(CourseUnitModel unitData)
        {
            try
            {
                var unit = mapper.Map<Course_Units>(unitData);

                var savingStatus = courseUnitService.Create(unit);

                if (savingStatus == Common.SavingStatus.Saved)
                {
                    return Json(new { saved = true });
                }
                else if (savingStatus == Common.SavingStatus.Exists)
                {
                    return Json(new { saved = false, message = "exists" });
                }
                else
                {
                    return Json(new { saved = false });
                }
            }
            catch (Exception ex)
            {
                return Json(new { saved = false, message = ex.Message });
            }
        }

        // GET: Admin/CourseUnits/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/CourseUnits/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestApp/Areas/Admin/Controllers/TraineeController.cs
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesApp.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin")]
    public class TraineeController : Controller
    {
        private readonly TraineeCourseService traineeCourseService;
        private readonly IMapper mapper;

        public TraineeController()
        {
            traineeCourseService= new TraineeCourseService();
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Admin/Trainee
        public ActionResult Index(int? cId)
        {
            if(cId == null)
                return RedirectToAction("Index", "Default", new {area = "admin"});


            var trainees = traineeCourseService.GetTrainees(cId.Value);

            var courseTrainees = mapper.Map<IEnumerable<Trainee_Courses>, IEnumerable<TraineeCourseModel>>(trainees);
            return View(courseTrainees);
        }
    }
}

TestApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CoursesApp.Data;
using CoursesApp.Models;
using CoursesApp.Services;
using Microsoft.AspNet.Identity;

namespace CoursesApp.Controllers
{
    public class CourseController : Controller
    {

        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        private readonly TraineeCourseService traineeCourseService;
        private readonly IMapper mapper;

        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();
            traineeCourseService = new TraineeCourseService();

        }

        //// GET: Default
        //public ActionResult Index()
        //{
        //    var courses = courseService.ReadAll();
        //    return View(mapper.Map<List<Course>, List<CourseModel>>(courses));
        //}

        // GET: Course
        public ActionResult Index(string query = null, int? categoryId = null, int? trainerId = null)
        {
            var coursesListData = new CoursesListModel();
            InitSelectList(ref coursesListData);


            var coursesList = courseService.ReadAll(query, trainerId, categoryId);


            var mappedCoursesList = mapper.Map<List<CourseModel>>(coursesList);
            coursesListData.Courses = mappedCoursesList;


            return View(coursesListData);
        }

        public ActionResult Info(int? Id)
        {
            if (Id == null || Id == 0)
                return HttpNotFound("This course not found!");

            var courseInfo = courseService.Get(Id.Value);
            if (courseInfo == null)
                return HttpNotFound("This course not found!");

            var mappedCourseInfo = mapper.Map<Course, CourseModel>(courseInfo);

            return View(mappedCourseInfo);
        }

        [HttpPost]
        public ActionResult Subscribe(TraineeCourseModel model, int Id)
        {
            try
            {
                var course = courseService.Get(Id);

                model.CourseId = Id;
                model.Trainee_Id = Id;

                var courseTrainee = mapper.Map<Trainee_Courses>(model);

                var TraineeCourse = traineeCourseService.Create(courseTrainee);

                if (TraineeCourse >= 1)
                {
                    return Json(new { saved = true });
                }
                else
                {
                    return Json(new { saved = false });
                }
            }
            catch (Exception ex)
            {
                return Json(new { saved = false, message = ex.Message });
            }
        }


        private void InitSelectList(ref CourseModel courseModel)
        {
            var mappedCategoriesList = GetCategories();
            courseModel.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            courseModel.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private void InitSelectList(ref CoursesListModel coursesList)
        {
            var mappedCategoriesList = GetCategories();
            coursesList.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            coursesList.Trainers = new SelectList(mappedTrainersList, "ID", "Name");
        }

        private IEnumerable<CategoryModel> GetCategories()
        {
            var categories = categoryService.ReadAll();
            return mapper.Map<IEnumerable<CategoryModel>>(categories);
        }

        private IEnumerable<TrainerModel> GetTrainers()
        {
            var trainers = trainerService.ReadAll();
            return mapper.Map<IEnumerable<TrainerModel>>(trainers);
        }

    }
}

TestApp/Areas/Admin/Views/Course/Create.cshtml
@model CoursesApp.Models.CourseModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Course", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id, Model.Categories, new { @class = " selectpicker", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trainer_Id, Model.Trainers, new { @class = " selectpicker", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })
                @Html.ValidationMessageFor(model => model.Trainer_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />


        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Image_ID, "Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" />
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestApp/Areas/Admin/Views/Course/Edit.cshtml
@model CoursesApp.Models.CourseModel

@{
    ViewBag.Title = "Update Course";
}

<h2>Update Course</h2>

@using (Html.BeginForm("Edit", "Course", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Image_ID)
    @Html.HiddenFor(model => model.Course_Id)
    @Html.HiddenFor(model => model.Creation_Date)

    <div class="form-group">
        @Html.LabelFor(model => model.Name,  new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />


    <div class="form-group">
        @Html.LabelFor(model => model.Category_Id,  new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Category_Id, Model.Categories, new { @class = "form-control", data_style = "btn-white btn-lg border border-2" })
            @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer_Id,  new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Trainer_Id, Model.Trainers, new { @class = "form-control", data_style = "btn-white btn-lg border border-2" })
            @Html.ValidationMessageFor(model => model.Trainer_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />


    <div class="form-group">
        @Html.LabelFor(model => model.Description,  new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.Image_ID, "Image",  new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" id="ImageFile" />
        </div>
    </div>
    <br />


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestApp/Areas/Admin/Views/Course/Index.cshtml
@model CoursesApp.Models.CoursesListModel

@{
    ViewBag.Title = "Courses";
}

<h2>Courses</h2>
<hr />

<p>
    @Html.ActionLink("Create New", "Create")
</p>



@using (Html.BeginForm("Index", "Course", FormMethod.Get, new { @class = "flex-row align-items-center flex-wrap " }))
{
    <div class="row mb-5">
        <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0 select">
            @*<input type="text" class="form-control form-control-lg" placeholder="Job title, Company...">*@
            @Html.TextBoxFor(m => m.Query, new { @class = "form-control form-control-lg", placeholder = "Course..." })
        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

            @Html.DropDownListFor(m => m.TrainerId, Model.Trainers, "Select Trainer", new { @class = " selectpicker", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })

        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

            @Html.DropDownListFor(m => m.CategoryId, Model.Categories, "Select Category", new { @class = "selectpicker", id = "job-Type", data_style = "btn-white btn-lg border border-2", data_width = "100%", data_live_search = "true" })
        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
            <button type="submit" value="Search" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Course</button>
        </div>
    </div>
}




<br />



<div class="table-responsive">
    <table class="table table-striped custom-table">
        <thead>
            <tr class="active">
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Creation Date</th>
                <th scope="col">Trainer Name</th>
                <th scope="col">Category Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Courses)
            {
                <tr scope="row">
                    <td>
                        <img src="~/Uploads/Courses/@item.Image_ID" style="width: 75px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Creation_Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrainerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category_Name)
                    </td>
                    <td>
                        @Html.ActionLink("Trainees", "Index", "Trainee", new { cId = item.Course_Id },
                                                new { @class = "btn btn-primary" })
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Course_Id })
                    </td>
                    <td>
                        @Html.ActionLink("Contents", "Index", "CourseUnits", new { courseId = item.Course_Id }, new { @class = "btn btn-primary" })
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal_@item.Course_Id" data-id="@item.Course_Id">
                            Delete
                        </button>


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal_@item.Course_Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <form>
                                            <div class="form-group">
                                                <label for="recipient-name" class="col-form-label">Are you sure you want to remove @item.Name</label>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        @using (Html.BeginForm("DeleteConfirmed", "Course", new { Id = item.Course_Id }, FormMethod.Post, null))
                                        {
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>

            }

        </tbody>
    </table>
</div>